[metadata]
name = spp_extended_theory
version = 0.1.0
author = Thibault J.-Y. Derrien
author_email = derrien@fzu.cz
description = Macroscopic polaritonics, Keldysh and Floquet theories
long_description = file: README.md
long_description_content_type = text/markdown
url=https://bitbucket.org/tjyderrien/spp_extended_theory/
project_urls=
	Bug Tracker = https://bitbucket.org/tjyderrien/spp_extended_theory/issues

[options]
packages = find:
include_package_data = True
install_requires =
    numpy>=1.18
python_requires = >=3

[options.packages.find]
exclude =
    tests

[flake8]
disable = C0330, C0326
max-line-length = 130
